### ISSUE TITLE
Webpack build fails in next.js typescript starter

### ISSUE THREAD

**Issue by adsc** [adrian2x/atomic-fns#8]
```
adsc@tp13:~/projects/atomictest$ npm run build

> atomictest@0.1.0 build
> next build

info  - Linting and checking validity of types  
info  - Creating an optimized production build  
Failed to compile.

HookWebpackError: Cannot mix BigInt and other types, use explicit conversions
    at makeWebpackError (/home/adsc/projects/atomictest/node_modules/next/dist/compiled/webpack/bundle5.js:28:308185)
    at /home/adsc/projects/atomictest/node_modules/next/dist/compiled/webpack/bundle5.js:28:105236
    at eval (eval at create (/home/adsc/projects/atomictest/node_modules/next/dist/compiled/webpack/bundle5.js:13:28771), <anonymous>:27:1)
    at /home/adsc/projects/atomictest/node_modules/next/dist/compiled/webpack/bundle5.js:28:68649
    at /home/adsc/projects/atomictest/node_modules/next/dist/build/webpack/plugins/next-trace-entrypoints-plugin.js:414:143
-- inner error --
TypeError: Cannot mix BigInt and other types, use explicit conversions
    at Object.BinaryExpression (/home/adsc/projects/atomictest/node_modules/next/dist/compiled/@vercel/nft/index.js:1:62490)
    at async computePureStaticValue (/home/adsc/projects/atomictest/node_modules/next/dist/compiled/@vercel/nft/index.js:1:21246)
    at async Object.enter (/home/adsc/projects/atomictest/node_modules/next/dist/compiled/@vercel/nft/index.js:1:28035)
    at async AsyncWalker.visit (/home/adsc/projects/atomictest/node_modules/next/dist/compiled/@vercel/nft/index.js:6:78333)
    at async AsyncWalker.visit (/home/adsc/projects/atomictest/node_modules/next/dist/compiled/@vercel/nft/index.js:6:78872)
    at async AsyncWalker.visit (/home/adsc/projects/atomictest/node_modules/next/dist/compiled/@vercel/nft/index.js:6:78791)
    at async AsyncWalker.visit (/home/adsc/projects/atomictest/node_modules/next/dist/compiled/@vercel/nft/index.js:6:78872)
    at async AsyncWalker.visit (/home/adsc/projects/atomictest/node_modules/next/dist/compiled/@vercel/nft/index.js:6:78791)
    at async AsyncWalker.visit (/home/adsc/projects/atomictest/node_modules/next/dist/compiled/@vercel/nft/index.js:6:78872)
    at async AsyncWalker.visit (/home/adsc/projects/atomictest/node_modules/next/dist/compiled/@vercel/nft/index.js:6:78791)
caused by plugins in Compilation.hooks.processAssets
TypeError: Cannot mix BigInt and other types, use explicit conversions
    at Object.BinaryExpression (/home/adsc/projects/atomictest/node_modules/next/dist/compiled/@vercel/nft/index.js:1:62490)
    at async computePureStaticValue (/home/adsc/projects/atomictest/node_modules/next/dist/compiled/@vercel/nft/index.js:1:21246)
    at async Object.enter (/home/adsc/projects/atomictest/node_modules/next/dist/compiled/@vercel/nft/index.js:1:28035)
    at async AsyncWalker.visit (/home/adsc/projects/atomictest/node_modules/next/dist/compiled/@vercel/nft/index.js:6:78333)
    at async AsyncWalker.visit (/home/adsc/projects/atomictest/node_modules/next/dist/compiled/@vercel/nft/index.js:6:78872)
    at async AsyncWalker.visit (/home/adsc/projects/atomictest/node_modules/next/dist/compiled/@vercel/nft/index.js:6:78791)
    at async AsyncWalker.visit (/home/adsc/projects/atomictest/node_modules/next/dist/compiled/@vercel/nft/index.js:6:78872)
    at async AsyncWalker.visit (/home/adsc/projects/atomictest/node_modules/next/dist/compiled/@vercel/nft/index.js:6:78791)
    at async AsyncWalker.visit (/home/adsc/projects/atomictest/node_modules/next/dist/compiled/@vercel/nft/index.js:6:78872)
    at async AsyncWalker.visit (/home/adsc/projects/atomictest/node_modules/next/dist/compiled/@vercel/nft/index.js:6:78791)


> Build failed because of webpack errors
```

Steps to reproduce:
1. Install next.js starter with typescript (use default settings) `npx create-next-app@latest --ts`
2. Install atomic-fns `npm i atomic-fns`
3. Put the following code into `pages/index.tsx`, save, then build the project with `npm run build`:

```
import Head from 'next/head'
import { get } from "atomic-fns"

export default function Home() {
    const data = {
        id: 1,
    }
    return (
        <>
            <Head>
                <title>Create Next App</title>
            </Head>
            <main>
                <p>{get("id", data)}</p>
            </main>
        </>
    )
}
```

**Comment by adrian2x** [comment]
Thanks for providing a way to reproduce the issue @adsc ! I'll release a fix for webpack builds shortly!

**Comment by adrian2x** [comment]
@adsc  For me, the build was successful. I tried the exact same steps you outlined, and I ran correctly the first time.
Maybe the issue could be caused by your webpack version?

```
> atomictest@0.1.0 build
> next build

info  - Linting and checking validity of types  
info  - Compiled successfully
info  - Collecting page data  
info  - Generating static pages (3/3)
info  - Finalizing page optimization  

Route (pages)                              Size     First Load JS
┌ ○ /                                      465 B          73.7 kB
├   /_app                                  0 B            73.3 kB
├ ○ /404                                   182 B          73.4 kB
└ λ /api/hello                             0 B            73.3 kB
+ First Load JS shared by all              74 kB
  ├ chunks/framework-2c79e2a64abdb08b.js   45.2 kB
  ├ chunks/main-0ecb9ccfcb6c9b24.js        27 kB
  ├ chunks/pages/_app-5fbdfbcdfb555d2f.js  296 B
  ├ chunks/webpack-8fa1640cc84ba8fe.js     750 B
  └ css/876d048b5dab7c28.css               706 B

λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)

info  - Creating an optimized production build ..%   
```

I also put together a repro here that works: https://stackblitz.com/edit/react-2yvteu?file=src%2FApp.js

**Comment by adrian2x** [comment]
@adsc I cloned your repo and it also works out of the box.
